### ISSUE TITLE
bug: v0.0.7 Provider produced inconsistent result after apply: .encryption_assumed_role_identifier was null

### ISSUE THREAD

**Issue by martijnvdp** [ClickHouse/terraform-provider-clickhouse#55]
when i create a new clickhouse cloud service with version 0.0.7 of the provider i get the following terraform error 
```
Error: Provider produced inconsistent result after apply
When applying changes to clickhouse_service.hubble_timescape_sandbox, provider "provider[\"registry.terraform.io/clickhouse/clickhouse\"]" produced an unexpected new value: .encryption_assumed_role_identifier: was null, but now cty.StringVal("").

This is a bug in the provider, which should be reported in the provider's own issue tracker.
```

revert to version v0.0.6 fixes the issue and the instance gets created without errors

Terraform
 version v1.6.4

**Comment by hcch0** [comment]
can you ask the user to "please share your terraform TF file"

**Comment by hcch0** [comment]
Hi, did you make changes to `encryption_assumed_role_identifier`

**Comment by fs-lewis-fogden** [comment]
Good afternoon,

I'm also getting this issue.

`
Error: Provider produced inconsistent result after apply

When applying changes to clickhouse_service, provider "registry.terraform.io/clickhouse/clickhouse" produced an unexpected new value: .encryption_key: was null, but now cty.StringVal("").

This is a bug in the provider, which should be reported in the provider's own issue tracker.

Error: Provider produced inconsistent result after apply

When applying changes to clickhouse_service, provider "registry.terraform.io/clickhouse/clickhouse" produced an unexpected new value: .encryption_assumed_role_identifier: was null, but now cty.StringVal("").

This is a bug in the provider, which should be reported in the provider's own issue tracker.
`

This occurs when settings `encryption_key` and `encryption_assumed_role_identifier" to `null` or not including the attributes, if CMEK is not required. The returned state value is an empty string `""`, but the input value is `null`, causing the discrepancy.

From a quick glance, it may be due to lines `931` and `932` in `service.go`:

`	
state.EncryptionKey = types.StringValue(service.EncryptionKey)
state.EncryptionAssumedRoleIdentifier = types.StringValue(service.EncryptionAssumedRoleIdentifier)
`

As the state is cast into a String, regardless of whether the value is null or not.

**Comment by martijnvdp** [comment]
i indeed did not include a encryption key

**Comment by hcch0** [comment]
Thank you. I will provide a fix for this by early next week.

**Comment by cdipesa-stord** [comment]
I am also running into this bug: 
 
`Error:Providerproducedinconsistentresultafterapply

Whenapplyingchangesto
module.clickhouse_service_prod.clickhouse_service.this,provider
"provider[\"registry.terraform.io/clickhouse/clickhouse\"]"producedan
unexpectednewvalue:.idle_timeout_minutes:wascty.NumberIntVal(0),but
nowcty.NumberIntVal(15).

Thisisabugintheprovider,whichshouldbereportedintheprovider's
ownissuetracker.`

I am setting `idle_timeout_minutes = 0` to disable idling in a production environment.

**Comment by hcch0** [comment]
The fix is taking longer than anticipated. 

Please use version v0.0.6 for now. Thank you.

**Comment by martijnvdp** [comment]
also seem to get it with 0.0.6 when i try to use this tf code
```
resource "clickhouse_service" "hubble_timescape" {
  cloud_provider              = "aws"
  idle_timeout_minutes    = 5
  max_total_memory_gb  = 24
  min_total_memory_gb  = 24
  name                            = "name"
  password                     = var.clickhouse_service_password
  region                          = "eu-west-1"
  tier                               = "production"
  private_endpoint_ids   = [data.terraform_remote_state.vpc.outputs.clickhouse_endpoint.id]
  ip_access                     =  ["0.0.0.0/0"] 
}
```

**Comment by martijnvdp** [comment]
seems a genaral issue due the use of empty strings as null values
think in my case the work around is setting   `encryption_assumed_role_identifier = ""`
